*** SERVICIOS
CLOSE DATA
CLOSE INDEX

select 1
use afiafi   index afiafi1,afiafi2,afiafi3
select 4
use syspac   index syspac, syspac2, syspac3

select 5
use serdata
select 6
use serdcge  index serdcge,serdcge2,serdcge3,serdcge4,serdcge5
select 7
use serdcde  index serdcde

select 8
use almart   index almart,almart2, almart3
select 9
use almtra   index almtra1,almtra2,almtra3
select 10
use almlot   index almlot
select 11
use almlottr index almlottr
select 12
use almdata

select 13
use syspto   index syspto
select 14
use sysservi index sysservi
select 15
use admadm   index admadm1,admadm2,admadm3
select 16
use sysuserd index sysuserd
select 17
use sysmed   index sysmed1,sysmed2,sysmed3
select 18
use sysesp   index sysesp

select 19
use faccxc   index faccxc1,faccxc2,faccxc3
select 20
use faccxctr index faccxct1,faccxct2,faccxct3

select 21 
use facdcge index facdcge2

RETURN
